name: CI/CD workflow 
on:
  push:
   branches:
     - master
jobs:
  buildandDeploy:
    env:
      imagename: "actionsimage"
    runs-on: ubuntu-latest
    steps:
     - name: Clone the code
       uses: actions/checkout@v4
     - name: Download Java and Maven
       uses: actions/setup-java@v4
       with: 
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
     - name: Setup Docker 
       uses: docker/setup-buildx-action@v3
     - name: Build the code 
       run: mvn package
     - name: Loginto Dockerhub 
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push Image to dockerhub 
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.imagename }}:latest
